apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jmeter-grafana-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - drgrafana.westus2.cloudapp.azure.com
    secretName: tls-secret-staging
  rules:
  - host: drgrafana.westus2.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: jmeter-grafana
          servicePort: 3000
        path: /(.*)