apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
  namespace: {{.Values.metadata.namespace.jmeter}}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jmeter-grafana
  namespace: {{.Values.metadata.namespace.jmeter}}
  labels:
    app: jmeter-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-grafana
  template:
    metadata:
      labels:
        app: jmeter-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
            protocol: TCP
          volumeMounts:
          - name: grafanavol
            mountPath: /var/lib/grafana
      volumes:
      - name: grafanavol
        persistentVolumeClaim:
          claimName: azure-managed-disk

---

apiVersion: v1
kind: Service
metadata:
  name: jmeter-grafana
  namespace: {{.Values.metadata.namespace.jmeter}}
  labels:
    app: jmeter-grafana
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: jmeter-grafana
